// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIXProject2
{
    internal sealed partial class Vsix
    {
        public const string Id = "Leetcode.bf57afd5-8c24-4f51-b61a-82fdf9d28e9b";
        public const string Name = "Leetcode Extension";
        public const string Description = @"Leetcode extension";
        public const string Language = "en-US";
        public const string Version = "1.1";
        public const string Author = "Anas";
        public const string Tags = "";
        public const bool IsPreview = false;
    }
}
